In [1]:
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, desc
from flask import Flask, jsonify, render_template, request
import csv

In [2]:
engine = create_engine("sqlite:///DataSets/bellybutton.sqlite")

In [3]:
Base = automap_base()
Base.prepare(engine, reflect=True)
Base.classes.keys()

['sample_metadata', 'samples']

In [4]:
Samples = Base.classes.samples
Sample_metadata = Base.classes.sample_metadata

In [5]:
session = Session(engine)

In [6]:
sample_names = Samples.__table__.columns
sample_names_ls = [name.key for name in sample_names]


sample_names_ls

['otu_id',
 'otu_label',
 '940',
 '941',
 '943',
 '944',
 '945',
 '946',
 '947',
 '948',
 '949',
 '950',
 '952',
 '953',
 '954',
 '955',
 '956',
 '958',
 '959',
 '960',
 '961',
 '962',
 '963',
 '964',
 '966',
 '967',
 '968',
 '969',
 '970',
 '971',
 '972',
 '973',
 '974',
 '975',
 '978',
 '1233',
 '1234',
 '1235',
 '1236',
 '1237',
 '1238',
 '1242',
 '1243',
 '1246',
 '1253',
 '1254',
 '1258',
 '1259',
 '1260',
 '1264',
 '1265',
 '1273',
 '1275',
 '1276',
 '1277',
 '1278',
 '1279',
 '1280',
 '1281',
 '1282',
 '1283',
 '1284',
 '1285',
 '1286',
 '1287',
 '1288',
 '1289',
 '1290',
 '1291',
 '1292',
 '1293',
 '1294',
 '1295',
 '1296',
 '1297',
 '1298',
 '1308',
 '1309',
 '1310',
 '1374',
 '1415',
 '1439',
 '1441',
 '1443',
 '1486',
 '1487',
 '1489',
 '1490',
 '1491',
 '1494',
 '1495',
 '1497',
 '1499',
 '1500',
 '1501',
 '1502',
 '1503',
 '1504',
 '1505',
 '1506',
 '1507',
 '1508',
 '1510',
 '1511',
 '1512',
 '1513',
 '1514',
 '1515',
 '1516',
 '1517',
 '1518',
 '1519',
 '1521',
 '1524',
 '1526',
 '1527',
 '1530',
 '1531',
 '1532',
 '1533',
 '1534',
 '1535',
 '1536',
 '1537',
 '1539',
 '1540',
 '1541',
 '1542',
 '1543',
 '1544',
 '1545',
 '1546',
 '1547',
 '1548',
 '1549',
 '1550',
 '1551',
 '1552',
 '1553',
 '1554',
 '1555',
 '1556',
 '1557',
 '1558',
 '1561',
 '1562',
 '1563',
 '1564',
 '1572',
 '1573',
 '1574',
 '1576',
 '1577',
 '1581',
 '1601']

In [30]:
otu_data = session.query(Samples).first()
otu_data.__dict__

{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x10ab6b198>,
 '973': 0,
 '1286': None,
 '1542': 0,
 '1558': 0,
 '974': 0,
 '1287': 0,
 '1543': 0,
 '1561': 0,
 '975': 0,
 '1288': 0,
 '1544': 0,
 '1562': 0,
 '978': 0,
 '1289': 0,
 '1545': 0,
 '1563': 0,
 '1233': 0,
 '1290': 0,
 '1546': 0,
 '1564': 0,
 '1234': 0,
 '1291': 0,
 '1547': 0,
 '1572': 0,
 '1235': 0,
 '1292': 0,
 '1548': 0,
 '1573': 0,
 '1236': 0,
 '1293': 0,
 '1549': 0,
 '1574': 0,
 '1237': 0,
 '1294': 0,
 '1550': 0,
 '1576': 0,
 '1238': 0,
 '1295': 0,
 '1551': 0,
 '1577': 0,
 '1242': 0,
 '1296': 0,
 '1552': 0,
 '1581': 0,
 '1243': 0,
 '1297': 0,
 '1553': 0,
 '1601': 0,
 '1246': 0,
 '1298': 0,
 '1554': 0,
 '1253': 0,
 '1308': 0,
 '1555': 0,
 '1254': 0,
 '1309': 0,
 '1556': 0,
 '1258': 0,
 '1310': 0,
 '1557': 0,
 '954': 0,
 '955': 0,
 '1259': 0,
 '1374': 0,
 '1502': 0,
 '1519': 0,
 '953': 0,
 '956': 0,
 '1260': 0,
 '1415': 0,
 '1503': 0,
 '1521': 0,
 '952': 0,
 '958': 0,
 '1264': 0,
 '1439': 0,
 '1504': 0,
 '1524': 0,
 '950': 0,
 '959': 0,
 '1265': 0,
 '1441': 0,
 '1505': 0,
 '1526': 0,
 '949': 0,
 '960': 0,
 '1273': 0,
 '1443': 0,
 '1506': 0,
 '1527': 0,
 '948': 0,
 '961': 0,
 '1275': 0,
 '1486': 0,
 '1507': 0,
 '1530': 0,
 '947': 0,
 '962': 0,
 '1276': 0,
 '1487': 0,
 '1508': 0,
 '1531': 0,
 '946': 0,
 '963': 0,
 '1277': 0,
 '1489': 0,
 '1510': 0,
 '1532': 0,
 '945': 0,
 '964': 0,
 '1278': 0,
 '1490': 0,
 '1511': 0,
 '1533': 0,
 '944': 0,
 '966': 1,
 '1279': 0,
 '1491': 0,
 '1512': 0,
 '1534': 0,
 '943': 0,
 '967': 0,
 '1280': 0,
 '1494': 0,
 '1513': 0,
 '1535': 0,
 '941': 0,
 '968': 0,
 '1281': 0,
 '1495': 0,
 '1514': 0,
 '1536': 0,
 '940': 0,
 '969': 0,
 '1282': 0,
 '1497': 0,
 '1515': 0,
 '1537': 0,
 'otu_label': 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
 '970': 0,
 '1283': 0,
 '1499': 0,
 '1516': 0,
 '1539': 0,
 'otu_id': 1,
 '971': 0,
 '1284': 0,
 '1500': 0,
 '1517': 0,
 '1540': 0,
 '972': 0,
 '1285': 0,
 '1501': 0,
 '1518': 0,
 '1541': 0}